
export const APPROVAL_LIST_REQUEST = 'APPROVAL_LIST_REQUEST';
export const APPROVAL_LIST_SUCCESS = 'APPROVAL_LIST_SUCCESS';
export const APPROVAL_LIST_FAILURE = 'APPROVAL_LIST_FAILURE';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAILURE = 'COMMENT_LIST_FAILURE';