export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAILURE = 'PAYMENT_LIST_FAILURE';

export const POLICY_LIST_REQUEST = 'POLICY_LIST_REQUEST';
export const POLICY_LIST_SUCCESS = 'POLICY_LIST_SUCCESS';
export const POLICY_LIST_FAILURE = 'POLICY_LIST_FAILURE';

export const POLICY_PROGRESS_LIST_REQUEST = 'POLICY_PROGRESS_LIST_REQUEST';
export const POLICY_PROGRESS_LIST_SUCCESS = 'POLICY_PROGRESS_LIST_SUCCESS';
export const POLICY_PROGRESS_LIST_FAILURE = 'POLICY_PROGRESS_LIST_FAILURE';