export const CURRENTCY_LIST_REQUEST = 'CURRENTCY_LIST_REQUEST';
export const CURRENTCY_LIST_SUCCESS = 'CURRENTCY_LIST_SUCCESS';
export const CURRENTCY_LIST_FAILURE = 'CURRENTCY_LIST_FAILURE';

export const CURRENTCY_DETAIL_REQUEST = 'CURRENTCY_DETAIL_REQUEST';
export const CURRENTCY_DETAIL_SUCCESS = 'CURRENTCY_DETAIL_SUCCESS';
export const CURRENTCY_DETAIL_FAILURE = 'CURRENTCY_DETAIL_FAILURE';

export const CURRENTCY_EDIT_REQUEST = 'CURRENTCY_EDIT_REQUEST';
export const CURRENTCY_EDIT_SUCCESS = 'CURRENTCY_EDIT_SUCCESS';
export const CURRENTCY_EDIT_FAILURE = 'CURRENTCY_EDIT_FAILURE';

export const CURRENTCY_ADD_REQUEST = 'CURRENTCY_ADD_REQUEST';
export const CURRENTCY_ADD_SUCCESS = 'CURRENTCY_ADD_SUCCESS';
export const CURRENTCY_ADD_FAILURE = 'CURRENTCY_ADD_FAILURE';  