export const REGION_LIST_REQUEST = 'REGION_LIST_REQUEST';
export const REGION_LIST_SUCCESS = 'REGION_LIST_SUCCESS';
export const REGION_LIST_FAILURE = 'REGION_LIST_FAILURE';

export const PROVINCE_LIST_REQUEST = 'PROVINCE_LIST_REQUEST';
export const PROVINCE_LIST_SUCCESS = 'PROVINCE_LIST_SUCCESS';
export const PROVINCE_LIST_FAILURE = 'PROVINCE_LIST_FAILURE';

export const TYPE_LIST_REQUEST = 'TYPE_LIST_REQUEST';
export const TYPE_LIST_SUCCESS = 'TYPE_LIST_SUCCESS';
export const TYPE_LIST_FAILURE = 'TYPE_LIST_FAILURE';

export const STATUS_LIST_REQUEST = 'STATUS_LIST_REQUEST';
export const STATUS_LIST_SUCCESS = 'STATUS_LIST_SUCCESS';
export const STATUS_LIST_FAILURE = 'STATUS_LIST_FAILURE';