export const PROVINCE_LIST_REQUEST = 'PROVINCE_LIST_REQUEST';
export const PROVINCE_LIST_SUCCESS = 'PROVINCE_LIST_REQUEST';
export const PROVINCE_LIST_FAILURE = 'PROVINCE_LIST_REQUEST';

export const DISTRICT_LIST_REQUEST = 'DISTRICT_LIST_REQUEST';
export const DISTRICT_LIST_SUCCESS = 'DISTRICT_LIST_SUCCESS';
export const DISTRICT_LIST_FAILURE = 'DISTRICT_LIST_FAILURE';

export const WARD_LIST_REQUEST = 'WARD_LIST_REQUEST';
export const WARD_LIST_SUCCESS = 'WARD_LIST_SUCCESS';
export const WARD_LIST_FAILURE = 'WARD_LIST_FAILURE';
