export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAILURE = 'PROJECT_LIST_FAILURE';

export const PROJECT_DETAIL_REQUEST = 'PROJECT_DETAIL_REQUEST';
export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';
export const PROJECT_DETAIL_FAILURE = 'PROJECT_DETAIL_FAILURE';

export const PROJECT_EDIT_REQUEST = 'PROJECT_EDIT_REQUEST';
export const PROJECT_EDIT_SUCCESS = 'PROJECT_EDIT_SUCCESS';
export const PROJECT_EDIT_FAILURE = 'PROJECT_EDIT_FAILURE';

export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAILURE = 'PROJECT_ADD_FAILURE'; 

export const SELLOPEN_LIST_REQUEST = 'SELLOPEN_LIST_REQUEST';
export const SELLOPEN_LIST_SUCCESS = 'SELLOPEN_LIST_SUCCESS';
export const SELLOPEN_LIST_FAILURE = 'SELLOPEN_LIST_FAILURE';

export const BANKING_LIST_REQUEST = 'BANKING_LIST_REQUEST';
export const BANKING_LIST_SUCCESS = 'BANKING_LIST_SUCCESS';
export const BANKING_LIST_FAILURE = 'BANKING_LIST_FAILURE';

export const POLICY_SALE_LIST_REQUEST = 'POLICY_SALE_LIST_REQUEST';
export const POLICY_SALE_LIST_SUCCESS = 'POLICY_SALE_LIST_SUCCESS';
export const POLICY_SALE_LIST_FAILURE = 'POLICY_SALE_LIST_FAILURE';