export const REQUEST_DATA_REQUEST = 'REQUEST_DATA_REQUEST';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_FAILURE = 'REQUEST_DATA_FAILURE';

export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST';
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS';
export const PROMOTION_LIST_FAILURE = 'PROMOTION_LIST_FAILURE';

export const PROMOTION_PRODUCT_REQUEST = 'PROMOTION_PRODUCT_REQUEST';
export const PROMOTION_PRODUCT_SUCCESS = 'PROMOTION_PRODUCT_SUCCESS';
export const PROMOTION_PRODUCT_FAILURE = 'PROMOTION_PRODUCT_FAILURE';

export const CLEAR_DATA = 'CLEAR_DATA';