export const REQUEST_DATA_REQUEST = 'REQUEST_DATA_REQUEST';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_FAILURE = 'REQUEST_DATA_FAILURE';

export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST';
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS';
export const PROMOTION_LIST_FAILURE = 'PROMOTION_LIST_FAILURE';